Description: >
    Agnes Project2 / Udacity
    
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
Resources:
  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
         Fn::ImportValue:
           !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
         Fn::ImportValue:
           !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  WebAppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              apt-get update -y
              apt-get install unzip awscli -y
              apt-get install apache2 -y
              systemctl start apache2.service
              cd /var/www/html
              aws s3 cp s3://udacity-demo-1/udacity.zip .
              unzip -o udacity.zip
          ImageId: ami-0c5204531f799e0c6
          SecurityGroups:
          - Ref: ServerSecurityGroup
          InstanceType: t2.medium
          BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: '10'
  WebAppGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
          VPCZoneIdentifier:
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PRIV-NETS"
          LaunchConfigurationName: 
            Ref: WebAppLaunchConfig
          MinSize: '3'
          MaxSize: '5'
  WebAppLB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
          Subnets:
          - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
          SecurityGroups: 
          - Ref: LBSecurityGroup        
  Listener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
          DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: WebAppTargetGroup
          LoadBalancerArn:
            Ref: WebAppLB
          Port: '80'
          Protocol: HTTP        
  ALBListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
          Actions:
          - Type: forward
            TargetGroupArn: !Ref 'WebAppTargetGroup'
          Conditions:
          - Field: path-pattern
            Values: [/]
          ListenerArn: !Ref 'Listener'
          Priority: 1     
  WebAppTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
          HealthCheckIntervalSeconds: 10
          HealthCheckPath: /
          HealthCheckProtocol: HTTP
          HealthCheckTimeoutSeconds: 8
          HealthyThresholdCount: 2
          Port: 80
          Protocol: HTTP
          UnhealthyThresholdCount: 5
          VpcId: 
            Fn::ImportValue:
              Fn::Sub: "${EnvironmentName}-VPCID"
Outputs:

    LBSecurityGroup:
        Description: A reference to the created  LBSecurityGroup:
        Value: !Ref  LBSecurityGroup:
        Export:
          Name: !Sub ${EnvironmentName}-VPCID

      ServerSecurityGroup:
        Description: ServerSecurityGroup:
        Value: !Ref   ServerSecurityGroup:
        Export:
          Name: !Sub ${EnvironmentName}-VPCID

    WebAppLaunchConfig:
        Description: WebAppLaunchConfig
        Value: !Ref WebAppLaunchConfig
        Export:
          Name: !Sub ${EnvironmentName}-PRI1-RT

    WebAppGroup:
        Description: AutoScalingGroup
        Value: !Ref WebAppLaunchConfig
        Export:
          Name: !Sub ${EnvironmentName}-PRIV-NETS

    WebAppLB:
        Description: ElasticLoadBalancing
        Value: !Ref LBSecurityGroup
        Export:
          Name: !Sub ${EnvironmentName}-PUB1-SN
          Name: !Sub ${EnvironmentName}-PUB2-SN

    Listener:
        Description: Listener
        Value: !Ref WebAppLB
        Export:
          Name: !Sub ${EnvironmentName}-PRIV-NETS

    ALBListenerRule:
        Description: ListenerRule
        Value: !Ref WebAppTargetGroup
        Export:
          Name: !Sub ${EnvironmentName}-PUB1-SN

    WebAppTargetGroup: 
        Description: WebAppTargetGroup
        Value: !Ref TargetGroup
        Export:
          Name: !Sub ${EnvironmentName}-VPCID